language: ruby
rvm: 1.8.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y puppet
script: ./scripts/validate-manifests.sh
notifications:
  email:
      recipients:
        - gluthra@thoughtworks.com
      on_success: change
      on_failure: change